package obsdoc

// Initially generated by copying
// https://raw.githubusercontent.com/obsproject/obs-websocket/master/docs/generated/protocol.json
// into https://mholt.github.io/json-to-go/
//
// and then manually polished up.
type Protocol struct {
	Enums    []Enum    `json:"enums,omitempty"`
	Requests []Request `json:"requests,omitempty"`
	Events   []Event   `json:"events,omitempty"`
}
type EnumIdentifier struct {
	Description    string `json:"description,omitempty"`
	EnumIdentifier string `json:"enumIdentifier,omitempty"`
	RPCVersion     string `json:"rpcVersion,omitempty"`
	Deprecated     bool   `json:"deprecated,omitempty"`
	InitialVersion string `json:"initialVersion,omitempty"`
	EnumValue      any    `json:"enumValue,omitempty"`
}
type Enum struct {
	EnumType        string           `json:"enumType,omitempty"`
	EnumIdentifiers []EnumIdentifier `json:"enumIdentifiers,omitempty"`
}
type Field struct {
	ValueName             string `json:"valueName,omitempty"`
	ValueType             string `json:"valueType,omitempty"`
	ValueDescription      string `json:"valueDescription,omitempty"`
	ValueRestrictions     any    `json:"valueRestrictions,omitempty"`
	ValueOptional         bool   `json:"valueOptional,omitempty"`
	ValueOptionalBehavior any    `json:"valueOptionalBehavior,omitempty"`
}
type Request struct {
	Description    string  `json:"description,omitempty"`
	RequestType    string  `json:"requestType,omitempty"`
	Complexity     int     `json:"complexity,omitempty"`
	RPCVersion     string  `json:"rpcVersion,omitempty"`
	Deprecated     bool    `json:"deprecated,omitempty"`
	InitialVersion string  `json:"initialVersion,omitempty"`
	Category       string  `json:"category,omitempty"`
	RequestFields  []Field `json:"requestFields,omitempty"`
	ResponseFields []Field `json:"responseFields,omitempty"`
}
type Event struct {
	Description       string  `json:"description,omitempty"`
	EventType         string  `json:"eventType,omitempty"`
	EventSubscription string  `json:"eventSubscription,omitempty"`
	Complexity        int     `json:"complexity,omitempty"`
	RPCVersion        string  `json:"rpcVersion,omitempty"`
	Deprecated        bool    `json:"deprecated,omitempty"`
	InitialVersion    string  `json:"initialVersion,omitempty"`
	Category          string  `json:"category,omitempty"`
	DataFields        []Field `json:"dataFields,omitempty"`
}
